/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.gerenciamento;

import Controller.ControllerCurso;
import Controller.ControllerEvento;
import Controller.ControllerGerenciamento;
import Controller.ControllerInstituicaoEnsino;
import Controller.ControllerProfissao;

/**
 *
 * @author Felipe Fraga
 */
public class JFramePainelGerenciamento extends javax.swing.JFrame {

    private ControllerGerenciamento controllerGerenciamento;
    private ControllerInstituicaoEnsino controllerInstituicaoEnsino;
    private ControllerProfissao controllerProfissao;
    private ControllerCurso controllerCurso;

    /**
     * Creates new form JFramePainelGerenciamento
     */
    public JFramePainelGerenciamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jComboBoxInstituicaoEnsino = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonCursos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jComboBoxInstituicaoEnsino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médio", "Técnico","Superior","Mestrado","Doutorado","PHD" }));
        jComboBoxInstituicaoEnsino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInstituicaoEnsinoActionPerformed(evt);
            }
        });

        jLabel1.setText("Instituição de Ensino");

        jButton1.setText("Profissão");

        jButtonCursos.setText("Cursos");
        jButtonCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jComboBoxInstituicaoEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addComponent(jButtonCursos)
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInstituicaoEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButtonCursos))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxInstituicaoEnsinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInstituicaoEnsinoActionPerformed
        controllerInstituicaoEnsino = new ControllerInstituicaoEnsino();
        controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoMedio(false);
        controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoTecnico(false);
        controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoSuperior(false);
        controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoMestrado(false);
        controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoDoutorado(false);
        controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoPhd(false);
        controllerInstituicaoEnsino.getIntituicaoEnsino().setNome("");
        
        if (jComboBoxInstituicaoEnsino.getSelectedItem().equals("Médio")) {
            controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoMedio(true);
        } else if (jComboBoxInstituicaoEnsino.getSelectedItem().equals("Técnico")) {

            controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoTecnico(true);

        } else if (jComboBoxInstituicaoEnsino.getSelectedItem().equals("Superior")) {

            controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoSuperior(true);

        } else if (jComboBoxInstituicaoEnsino.getSelectedItem().equals("Mestrado")) {

            controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoMestrado(true);

        } else if (jComboBoxInstituicaoEnsino.getSelectedItem().equals("Doutorado")) {

            controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoDoutorado(true);

        } else if (jComboBoxInstituicaoEnsino.getSelectedItem().equals("PHD")) {

            controllerInstituicaoEnsino.getIntituicaoEnsino().setTipoPhd(true);
        }
        controllerInstituicaoEnsino.mostrar(this);
    }//GEN-LAST:event_jComboBoxInstituicaoEnsinoActionPerformed

    private void jButtonCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursosActionPerformed
       controllerCurso = new ControllerCurso();
       controllerCurso.mostrar(this);
    }//GEN-LAST:event_jButtonCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePainelGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePainelGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePainelGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePainelGerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePainelGerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCursos;
    private javax.swing.JComboBox<String> jComboBoxInstituicaoEnsino;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void setControllerGerenciamento(ControllerGerenciamento controllerGerenciamento) {
        this.controllerGerenciamento = controllerGerenciamento;
    }

    public void setControllerInstituicaoEnsino(ControllerInstituicaoEnsino controllerInstituicaoEnsino) {
        this.controllerInstituicaoEnsino = controllerInstituicaoEnsino;
    }

    public void setControllerProfissao(ControllerProfissao controllerProfissao) {
        this.controllerProfissao = controllerProfissao;
    }

    public void setControllerCurso(ControllerCurso controllerCurso) {
        this.controllerCurso = controllerCurso;
    }
}
