/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.curso;

import Controller.ControllerCurso;
import Controller.ControllerInstituicaoEnsino;
import Model.InstituicaoEnsino;

/**
 *
 * @author Felipe Fraga
 */
public class JFrameCadastrarCurso extends javax.swing.JFrame {

    private ControllerInstituicaoEnsino controllerInstituicaoEnsino;
    private ControllerCurso controllerCurso;

    /**
     * Creates new form JFrameCadastrarCurso
     */
    public JFrameCadastrarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTIpoCurso = new javax.swing.JComboBox<>();
        jTextFieldNomeInstituicao = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonCadastrarCurso = new javax.swing.JButton();
        jLabelErro1 = new javax.swing.JLabel();
        jLabelErro = new javax.swing.JLabel();
        jLabelErro2 = new javax.swing.JLabel();
        jPanelSecundario = new javax.swing.JPanel();
        jButtonNovaInstituicao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInsituicao = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);

        jLabel1.setText("Cadastrar Curso");

        jLabel2.setText("Nome:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Instituição de Ensino:");

        jComboBoxTIpoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Medio", "Tecnico","Superior","Mestrado","Doutorado","Phd"}));
        jComboBoxTIpoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTIpoCursoMouseClicked(evt);
            }
        });
        jComboBoxTIpoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTIpoCursoActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonCadastrarCurso.setVisible(false);
        jButtonCadastrarCurso.setText("Cadastrar");

        jLabelErro1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErro1.setText("*");
        jLabelErro1.setVisible(false);

        jLabelErro.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErro.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErro.setText("Preencha os campos para prosseguir");
        jLabelErro.setVisible(false);

        jLabelErro2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErro2.setText("*");
        jLabelErro2.setVisible(false);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButtonCadastrarCurso))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTIpoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelErro1))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonPesquisar))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelErro2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelErro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTIpoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErro1))
                .addGap(22, 22, 22)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNomeInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisar)))
                .addGap(32, 32, 32)
                .addComponent(jButtonCadastrarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 35, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErro2)
                    .addComponent(jLabelErro))
                .addContainerGap())
        );

        jPanelSecundario.setVisible(false);

        jButtonNovaInstituicao.setText("Cadastrar Nova Instituição de Enisno");
        jButtonNovaInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaInstituicaoActionPerformed(evt);
            }
        });

        jTableInsituicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableInsituicao);

        javax.swing.GroupLayout jPanelSecundarioLayout = new javax.swing.GroupLayout(jPanelSecundario);
        jPanelSecundario.setLayout(jPanelSecundarioLayout);
        jPanelSecundarioLayout.setHorizontalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSecundarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSecundarioLayout.createSequentialGroup()
                        .addComponent(jButtonNovaInstituicao)
                        .addGap(186, 186, 186)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelSecundarioLayout.setVerticalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNovaInstituicao)
                .addGap(19, 19, 19))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2)
            .addComponent(jPanelSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (!jComboBoxTIpoCurso.getSelectedItem().equals("")) {
            controllerInstituicaoEnsino.getIntituicaoEnsino().setNome(jTextFieldNomeInstituicao.getText());
            controllerInstituicaoEnsino.getInstituicaoEnsinoDAO().setTipo((String) jComboBoxTIpoCurso.getSelectedItem());
            jTableInsituicao.setModel(controllerInstituicaoEnsino.atualizar());
            jPanelSecundario.setVisible(true);
        } else {
            jLabelErro.setVisible(true);
            jLabelErro2.setVisible(true);
            jLabelErro1.setVisible(true);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonNovaInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaInstituicaoActionPerformed
        controllerInstituicaoEnsino.setControllerCurso(controllerCurso);
        controllerInstituicaoEnsino.getInstituicaoEnsinoDAO().setTipo((String) jComboBoxTIpoCurso.getSelectedItem());
        controllerInstituicaoEnsino.incluir(this);
        jPanelSecundario.setVisible(false);
        jTextFieldNomeInstituicao.setText(controllerInstituicaoEnsino.getInstituicaoEnsino().getNome());
        jButtonCadastrarCurso.setVisible(true);
    }//GEN-LAST:event_jButtonNovaInstituicaoActionPerformed

    private void jComboBoxTIpoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTIpoCursoMouseClicked
        if (jComboBoxTIpoCurso.getSelectedItem().equals("")) {
            jLabelErro.setVisible(true);
            jLabelErro2.setVisible(true);
            jLabelErro1.setVisible(true);
        } else {
            jLabelErro.setVisible(false);
            jLabelErro2.setVisible(false);
            jLabelErro1.setVisible(false);
        }

    }//GEN-LAST:event_jComboBoxTIpoCursoMouseClicked

    private void jComboBoxTIpoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTIpoCursoActionPerformed
        if (jComboBoxTIpoCurso.getSelectedItem().equals("")) {
            jLabelErro.setVisible(true);
            jLabelErro2.setVisible(true);
            jLabelErro1.setVisible(true);
        } else {
            jLabelErro.setVisible(false);
            jLabelErro2.setVisible(false);
            jLabelErro1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxTIpoCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastrarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCurso;
    private javax.swing.JButton jButtonNovaInstituicao;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBoxTIpoCurso;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelErro;
    private javax.swing.JLabel jLabelErro1;
    private javax.swing.JLabel jLabelErro2;
    private javax.swing.JPanel jPanelSecundario;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInsituicao;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeInstituicao;
    // End of variables declaration//GEN-END:variables

    public ControllerInstituicaoEnsino getControllerInstituicaoEnsino() {
        return controllerInstituicaoEnsino;
    }

    public void setControllerInstituicaoEnsino(ControllerInstituicaoEnsino controllerInstituicaoEnsino) {
        this.controllerInstituicaoEnsino = controllerInstituicaoEnsino;
    }

    public ControllerCurso getControllerCurso() {
        return controllerCurso;
    }

    public void setControllerCurso(ControllerCurso controllerCurso) {
        this.controllerCurso = controllerCurso;
    }

    public void setjTextFieldNomeInstituicao(javax.swing.JTextField jTextFieldNomeInstituicao) {
        this.jTextFieldNomeInstituicao = jTextFieldNomeInstituicao;
    }
}
