/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.InstituicaoEnsino;

import Controller.ControllerInstituicaoEnsino;

/**
 *
 * @author Felipe Fraga
 */
public class JFrameAlterarInstituicao extends javax.swing.JFrame {

    private ControllerInstituicaoEnsino controllerInstituicaoEnsino;

    /**
     * Creates new form JFrameAlterarInstituicao
     */
    public JFrameAlterarInstituicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLocal = new javax.swing.JTextField();
        jRadioButtonMedio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonTecnico = new javax.swing.JRadioButton();
        jRadioButtonSuperior = new javax.swing.JRadioButton();
        jRadioButtonMestrado = new javax.swing.JRadioButton();
        jRadioButtonDoutorado = new javax.swing.JRadioButton();
        jRadioButtonPHD = new javax.swing.JRadioButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Instituição de Ensino");

        jLabel2.setText("Nome:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel3.setText("Local:");

        jRadioButtonMedio.setText("Médio");

        jLabel4.setText("Tipo:");

        jRadioButtonTecnico.setText("Técnico");

        jRadioButtonSuperior.setText("Superior");

        jRadioButtonMestrado.setText("Mestrado");

        jRadioButtonDoutorado.setText("Doutorado");

        jRadioButtonPHD.setText("PHD");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 30, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonMedio)
                                    .addComponent(jRadioButtonMestrado))
                                .addGap(91, 91, 91)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTecnico)
                                    .addComponent(jRadioButtonDoutorado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonPHD)
                                    .addComponent(jRadioButtonSuperior))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar)
                        .addContainerGap())))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jButtonSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMedio)
                    .addComponent(jRadioButtonTecnico)
                    .addComponent(jRadioButtonSuperior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMestrado)
                    .addComponent(jRadioButtonDoutorado)
                    .addComponent(jRadioButtonPHD))
                .addGap(31, 31, 31)
                .addComponent(jButtonSalvar)
                .addGap(2, 2, 2)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int opcao = controllerInstituicaoEnsino.confirmaInformacoes();
        if (opcao == 0) {
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setNome(jTextFieldNome.getText());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setLocal(jTextFieldNome.getText());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setTipoMedio(jRadioButtonMedio.isSelected());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setTipoTecnico(jRadioButtonTecnico.isSelected());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setTipoSuperior(jRadioButtonSuperior.isSelected());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setTipoMestrado(jRadioButtonMestrado.isSelected());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setTipoDoutorado(jRadioButtonDoutorado.isSelected());
            getControllerInstituicaoEnsino().getInstituicaoEnsino().setTipoPhd(jRadioButtonPHD.isSelected());
            controllerInstituicaoEnsino.alterar(this);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        controllerInstituicaoEnsino.voltar(this);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        controllerInstituicaoEnsino.excluir(this);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarInstituicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonDoutorado;
    private javax.swing.JRadioButton jRadioButtonMedio;
    private javax.swing.JRadioButton jRadioButtonMestrado;
    private javax.swing.JRadioButton jRadioButtonPHD;
    private javax.swing.JRadioButton jRadioButtonSuperior;
    private javax.swing.JRadioButton jRadioButtonTecnico;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    public void setParametro() {
        jTextFieldNome.setText(getControllerInstituicaoEnsino().getInstituicaoEnsino().getNome());
        jTextFieldLocal.setText(getControllerInstituicaoEnsino().getInstituicaoEnsino().getLocal());
        if (getControllerInstituicaoEnsino().getInstituicaoEnsino().isTipoMedio()) {
            jRadioButtonMedio.setSelected(true);
        }
        if (getControllerInstituicaoEnsino().getInstituicaoEnsino().isTipoTecnico()) {
            jRadioButtonTecnico.setSelected(true);
        }
        if (getControllerInstituicaoEnsino().getInstituicaoEnsino().isTipoSuperior()) {
            jRadioButtonSuperior.setSelected(true);
        }
        if (getControllerInstituicaoEnsino().getInstituicaoEnsino().isTipoMestrado()) {
            jRadioButtonMestrado.setSelected(true);
        }
        if (getControllerInstituicaoEnsino().getInstituicaoEnsino().isTipoDoutorado()) {
            jRadioButtonDoutorado.setSelected(true);
        }
        if (getControllerInstituicaoEnsino().getInstituicaoEnsino().isTipoPhd()) {
            jRadioButtonPHD.setSelected(true);
        }
    }

    public ControllerInstituicaoEnsino getControllerInstituicaoEnsino() {
        return controllerInstituicaoEnsino;
    }

    public void setControllerInstituicaoEnsino(ControllerInstituicaoEnsino controllerInstituicaoEnsino) {
        this.controllerInstituicaoEnsino = controllerInstituicaoEnsino;
    }
}
