/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.AtividadeExtra;
import Classes.Endereco;
import Classes.Persistencia;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class JFrameAtividadeExtra extends javax.swing.JFrame {
    AtividadeExtra atividade = new AtividadeExtra ();
    String recebe;
    private PreparedStatement ps = null;
    public JFrameAtividadeExtra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFramePreenher = new javax.swing.JInternalFrame();
        jButtonSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonPesquisa = new javax.swing.JRadioButton();
        jRadioButtonEmpresa = new javax.swing.JRadioButton();
        jRadioButtonIntercambio = new javax.swing.JRadioButton();
        jRadioButtonOutros = new javax.swing.JRadioButton();
        jTextFieldOutra = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFramePreenher.setVisible(true);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Atividade Extra:");

        jRadioButtonPesquisa.setText("Pesquisa Científica");
        jRadioButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPesquisaActionPerformed(evt);
            }
        });

        jRadioButtonEmpresa.setText("Empresa Junior");
        jRadioButtonEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpresaActionPerformed(evt);
            }
        });

        jRadioButtonIntercambio.setText("Intercâmbio");
        jRadioButtonIntercambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIntercambioActionPerformed(evt);
            }
        });

        jRadioButtonOutros.setText("Outra");
        jRadioButtonOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOutrosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Data");

        jLabel4.setText("Horas de duração");

        jButton1.setText("Voltar");

        javax.swing.GroupLayout jInternalFramePreenherLayout = new javax.swing.GroupLayout(jInternalFramePreenher.getContentPane());
        jInternalFramePreenher.getContentPane().setLayout(jInternalFramePreenherLayout);
        jInternalFramePreenherLayout.setHorizontalGroup(
            jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPesquisa)
                    .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(32, 32, 32)
                            .addComponent(jButtonSalvar))
                        .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                            .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(91, 91, 91)
                                    .addComponent(jLabel2))
                                .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                    .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonEmpresa)
                                        .addComponent(jRadioButtonIntercambio)
                                        .addComponent(jRadioButtonOutros))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addComponent(jTextFieldOutra, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jInternalFramePreenherLayout.setVerticalGroup(
            jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPesquisa)
                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonIntercambio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOutros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOutra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButton1))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFramePreenher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFramePreenher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            ps = Persistencia.conexao().prepareStatement("INSERT into atividadeextra (nome, tipo, data, duracaoHoras) values ( ?, ?, ?, ?, ?, ?)");
            ps.setInt(1, atividade.getId());
            ps.setInt(2, atividade.getIdUsuario());
            ps.setString(3, jTextFieldNome.getText());
            ps.setString(4, recebe);
            ps.setString(5, jTextFieldData.getText());
            ps.setInt(6, Integer.parseInt(jTextFieldHoras.getText()));
            ps.executeUpdate();
            System.out.println("Atividade extra cadastrada com sucesso");
        } catch (SQLException e) {

            System.out.println("não foi possível execultar o comando sql para inserir" + e);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jRadioButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPesquisaActionPerformed
        if (jRadioButtonPesquisa.getVerifyInputWhenFocusTarget()){
            jRadioButtonEmpresa.setEnabled(false);
            jRadioButtonIntercambio.setEnabled(false);
            jRadioButtonOutros.setEnabled(false);
            jTextFieldOutra.setVisible(false);
            recebe = ("Pesquisa Cientifica");
        }
    }//GEN-LAST:event_jRadioButtonPesquisaActionPerformed

    private void jRadioButtonEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmpresaActionPerformed
        if (jRadioButtonEmpresa.getVerifyInputWhenFocusTarget()){
            jRadioButtonPesquisa.setEnabled(false);
            jRadioButtonIntercambio.setEnabled(false);
            jRadioButtonOutros.setEnabled(false);
            jTextFieldOutra.setVisible(false);
            recebe = ("Empresa Junior");
        }
    }//GEN-LAST:event_jRadioButtonEmpresaActionPerformed

    private void jRadioButtonIntercambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIntercambioActionPerformed
        if (jRadioButtonIntercambio.getVerifyInputWhenFocusTarget()){
            jRadioButtonPesquisa.setEnabled(false);
            jRadioButtonEmpresa.setEnabled(false);
            jRadioButtonOutros.setEnabled(false);
            jTextFieldOutra.setVisible(false);
            recebe = ("Intercambio");
        }
    }//GEN-LAST:event_jRadioButtonIntercambioActionPerformed

    private void jRadioButtonOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOutrosActionPerformed
        if (jRadioButtonOutros.getVerifyInputWhenFocusTarget()){
            jRadioButtonPesquisa.setEnabled(false);
            jRadioButtonEmpresa.setEnabled(false);
            jRadioButtonIntercambio.setEnabled(false);
            jTextFieldOutra.setVisible(true);
            recebe = jTextFieldOutra.getText();
        }
    }//GEN-LAST:event_jRadioButtonOutrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAtividadeExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAtividadeExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAtividadeExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAtividadeExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAtividadeExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JInternalFrame jInternalFramePreenher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonEmpresa;
    private javax.swing.JRadioButton jRadioButtonIntercambio;
    private javax.swing.JRadioButton jRadioButtonOutros;
    private javax.swing.JRadioButton jRadioButtonPesquisa;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldOutra;
    // End of variables declaration//GEN-END:variables
}
