/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Profissao;
import Classes.ProfissaoUsuario;
import Classes.Persistencia;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author User
 */
public class JFrameProfissaoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JFrameProfissaoUsuario
     */
    
    ProfissaoUsuario profissaoU = new ProfissaoUsuario ();
    private PreparedStatement ps = null;
    String recebe = " ";
    public JFrameProfissaoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFramePreenher = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDataIn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldDataTe = new javax.swing.JTextField();
        jRadioButtonEstagio = new javax.swing.JRadioButton();
        jRadioButtonPleno = new javax.swing.JRadioButton();
        jRadioButtonSenior = new javax.swing.JRadioButton();
        jRadioButtonSuCo = new javax.swing.JRadioButton();
        jRadioButtonGerencia = new javax.swing.JRadioButton();
        jRadioButtonDiretoria = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFramePreenher.setVisible(true);

        jLabel2.setText("Data de início: ");

        jLabel3.setText("Local de atuação:");

        jLabel8.setText("Data de término:");

        jRadioButtonSim.setText("Sim");
        jRadioButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSimActionPerformed(evt);
            }
        });

        jRadioButtonNao.setText("Não");
        jRadioButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNaoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel4.setText("Ainda em atividade?");

        jButtonVoltar.setText("Voltar");

        jRadioButtonEstagio.setText("Estágio");
        jRadioButtonEstagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstagioActionPerformed(evt);
            }
        });

        jRadioButtonPleno.setText("Pleno");
        jRadioButtonPleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPlenoActionPerformed(evt);
            }
        });

        jRadioButtonSenior.setText("Senior");
        jRadioButtonSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeniorActionPerformed(evt);
            }
        });

        jRadioButtonSuCo.setText("Supervisão/Coordenação");
        jRadioButtonSuCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSuCoActionPerformed(evt);
            }
        });

        jRadioButtonGerencia.setText("Gerencia");
        jRadioButtonGerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGerenciaActionPerformed(evt);
            }
        });

        jRadioButtonDiretoria.setText("Diretoria");
        jRadioButtonDiretoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDiretoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePreenherLayout = new javax.swing.GroupLayout(jInternalFramePreenher.getContentPane());
        jInternalFramePreenher.getContentPane().setLayout(jInternalFramePreenherLayout);
        jInternalFramePreenherLayout.setHorizontalGroup(
            jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePreenherLayout.createSequentialGroup()
                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jButtonVoltar)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonSalvar))
                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonEstagio)
                            .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel3))
                                    .addComponent(jRadioButtonPleno)
                                    .addComponent(jRadioButtonSenior)
                                    .addComponent(jRadioButtonSuCo)
                                    .addComponent(jRadioButtonGerencia)
                                    .addComponent(jRadioButtonDiretoria))
                                .addGap(113, 113, 113)
                                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDataIn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonSim)
                                        .addGap(6, 6, 6)
                                        .addComponent(jRadioButtonNao))
                                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldDataTe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jInternalFramePreenherLayout.setVerticalGroup(
            jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                        .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSim)
                            .addComponent(jRadioButtonNao))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDataIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldDataTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jInternalFramePreenherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVoltar)
                            .addComponent(jButtonSalvar)))
                    .addGroup(jInternalFramePreenherLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonEstagio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPleno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSuCo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGerencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDiretoria)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFramePreenher)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFramePreenher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            ps = Persistencia.conexao().prepareStatement("INSERT into profissaousuario (id, idProfissao, idUsuario, localAtuação, emAtividade, dataInicio, dataTermino) values (?, ?, ?, ?, ?, ?, ?)");
            ps.setInt(1, profissaoU.getId());
            ps.setInt(2, profissaoU.getIdProfissao());
            ps.setInt(3, profissaoU.getIdUsuario());
            ps.setString(4, recebe);
            ps.setBoolean(5, jRadioButtonSim.getVerifyInputWhenFocusTarget());
            ps.setString(6, jTextFieldDataIn.getText());
            ps.setString(7, jTextFieldDataTe.getText());
            ps.executeUpdate();
            System.out.println("Profissao cadastrada com sucesso");
        } catch (SQLException e) {
            System.out.println("não foi possível execultar o comando sql para inserir" + e);
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed
 
    private void jRadioButtonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNaoActionPerformed
        if (jRadioButtonSim.getVerifyInputWhenFocusTarget()){
            jRadioButtonSim.setEnabled(false);
            jTextFieldDataTe.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonNaoActionPerformed

    private void jRadioButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSimActionPerformed
        if (jRadioButtonNao.getVerifyInputWhenFocusTarget()){
            jRadioButtonNao.setEnabled(false);
            jTextFieldDataTe.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButtonSimActionPerformed

    private void jRadioButtonPlenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlenoActionPerformed
        if (jRadioButtonPleno.getVerifyInputWhenFocusTarget()){
            jRadioButtonDiretoria.setEnabled(false);
            jRadioButtonEstagio.setEnabled(false);
            jRadioButtonSuCo.setEnabled(false);
            jRadioButtonSenior.setEnabled(false);
            jRadioButtonGerencia.setEnabled(false);
            recebe = ("Pleno");
        }
    }//GEN-LAST:event_jRadioButtonPlenoActionPerformed

    private void jRadioButtonDiretoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDiretoriaActionPerformed
        if (jRadioButtonDiretoria.getVerifyInputWhenFocusTarget()){
            jRadioButtonPleno.setEnabled(false);
            jRadioButtonEstagio.setEnabled(false);
            jRadioButtonSuCo.setEnabled(false);
            jRadioButtonSenior.setEnabled(false);
            jRadioButtonGerencia.setEnabled(false);
            recebe = ("Diretoria");
        }
    }//GEN-LAST:event_jRadioButtonDiretoriaActionPerformed

    private void jRadioButtonEstagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstagioActionPerformed
        if (jRadioButtonEstagio.getVerifyInputWhenFocusTarget()){
            jRadioButtonPleno.setEnabled(false);
            jRadioButtonDiretoria.setEnabled(false);
            jRadioButtonSuCo.setEnabled(false);
            jRadioButtonSenior.setEnabled(false);
            jRadioButtonGerencia.setEnabled(false);
            recebe = ("Estagio");
        }
    }//GEN-LAST:event_jRadioButtonEstagioActionPerformed

    private void jRadioButtonSuCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSuCoActionPerformed
        if (jRadioButtonSuCo.getVerifyInputWhenFocusTarget()){
            jRadioButtonPleno.setEnabled(false);
            jRadioButtonDiretoria.setEnabled(false);
            jRadioButtonEstagio.setEnabled(false);
            jRadioButtonSenior.setEnabled(false);
            jRadioButtonGerencia.setEnabled(false);
            recebe = ("Supervisao/Coordenacao");
        }
    }//GEN-LAST:event_jRadioButtonSuCoActionPerformed

    private void jRadioButtonSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeniorActionPerformed
        if (jRadioButtonSenior.getVerifyInputWhenFocusTarget()){
            jRadioButtonPleno.setEnabled(false);
            jRadioButtonDiretoria.setEnabled(false);
            jRadioButtonEstagio.setEnabled(false);
            jRadioButtonSuCo.setEnabled(false);
            jRadioButtonGerencia.setEnabled(false);
            recebe = ("Senior");
        }
    }//GEN-LAST:event_jRadioButtonSeniorActionPerformed

    private void jRadioButtonGerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGerenciaActionPerformed
        if (jRadioButtonGerencia.getVerifyInputWhenFocusTarget()){
            jRadioButtonPleno.setEnabled(false);
            jRadioButtonDiretoria.setEnabled(false);
            jRadioButtonEstagio.setEnabled(false);
            jRadioButtonSenior.setEnabled(false);
            jRadioButtonSuCo.setEnabled(false);
            recebe = ("Gerencia");
        }
    }//GEN-LAST:event_jRadioButtonGerenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameProfissaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameProfissaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameProfissaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameProfissaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameProfissaoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JInternalFrame jInternalFramePreenher;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButtonDiretoria;
    private javax.swing.JRadioButton jRadioButtonEstagio;
    private javax.swing.JRadioButton jRadioButtonGerencia;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonPleno;
    private javax.swing.JRadioButton jRadioButtonSenior;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JRadioButton jRadioButtonSuCo;
    private javax.swing.JTextField jTextFieldDataIn;
    private javax.swing.JTextField jTextFieldDataTe;
    // End of variables declaration//GEN-END:variables
}
